# Generated by Django 3.0.5 on 2020-09-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_reviews', '0003_auto_20200909_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
