# Generated by Django 3.0.5 on 2020-09-09 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0002_auto_20200906_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
