# Generated by Django 3.0.5 on 2020-09-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0003_auto_20200909_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
